[theme]
base = "light"
primaryColor = "#0FA89B"
backgroundColor = "#F6FAF9"
secondaryBackgroundColor = "#E9F4F2"
textColor = "#1F3A3D"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[server]
enableXsrfProtection = true
